name: Code Quality - Docs

on:
  push:
    paths:
      - '.github/workflows/lint-docs.yml'
      - '.markdownlint-cli2.yaml'
      - '**.md'
  pull_request:
    paths:
      - '.github/workflows/lint-docs.yml'
      - '.markdownlint-cli2.yaml'
      - '**.md'

jobs:
  lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: '**/*.md'
